#ifndef THRESHOLDS_H
#define THRESHOLDS_H

#define DEMO_MODE true

#define SENSOR_0_POS 0.4f
#define SENSOR_1_POS 0.30000000000000004f
#define SENSOR_2_POS 0.2f

#define GATE_CLOSE_THRESHOLD 3.5f
#define NOTIFICATION_THRESHOLD 6.0f
#define GATE_OPEN_DELAY 1.0f

#define SENSOR_SPACING 0.1f
#define LAST_SENSOR_TO_CROSSING 0.2f
#define CROSSING_TO_INTERSECTION 0.2f

#define EXPECTED_HAND_SPEED 0.08f

#endif
